# Generated by Django 5.2.3 on 2025-07-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Warnung', 'verbose_name_plural': 'Warnungen'},
        ),
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['-last_seen'], 'verbose_name': 'Fehlerprotokoll', 'verbose_name_plural': 'Fehlerprotokolle'},
        ),
        migrations.AlterModelOptions(
            name='monitoringsettings',
            options={'verbose_name': 'Überwachungseinstellungen', 'verbose_name_plural': 'Überwachungseinstellungen'},
        ),
        migrations.AlterModelOptions(
            name='performancemetric',
            options={'ordering': ['-created_at'], 'verbose_name': 'Leistungsmetrik', 'verbose_name_plural': 'Leistungsmetriken'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name'], 'verbose_name': 'Plattform', 'verbose_name_plural': 'Plattformen'},
        ),
        migrations.AlterModelOptions(
            name='systemhealth',
            options={'ordering': ['-checked_at'], 'verbose_name': 'Systemzustand', 'verbose_name_plural': 'Systemzustände'},
        ),
        migrations.AddField(
            model_name='platform',
            name='color',
            field=models.CharField(choices=[('success', 'Grün (Live)'), ('warning', 'Orange (Test)'), ('info', 'Blau (Local)'), ('secondary', 'Grau (Inaktiv)')], default='info', max_length=15),
        ),
        migrations.AddField(
            model_name='platform',
            name='environment',
            field=models.CharField(choices=[('test', 'Test'), ('live', 'Live'), ('local', 'Local')], default='test', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('downtime', 'Plattform-Ausfall'), ('high_error_rate', 'Hohe Fehlerrate'), ('slow_response', 'Langsame Antwortzeit'), ('resource_usage', 'Hohe Ressourcennutzung'), ('database_issue', 'Datenbankproblem'), ('custom', 'Benutzerdefinierte Warnung')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch'), ('critical', 'Kritisch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('acknowledged', 'Bestätigt'), ('resolved', 'Gelöst')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='error_type',
            field=models.CharField(choices=[('500', 'Serverfehler (500)'), ('404', 'Nicht gefunden (404)'), ('403', 'Verboten (403)'), ('database', 'Datenbankfehler'), ('api', 'API-Fehler'), ('timeout', 'Timeout-Fehler'), ('other', 'Andere')], max_length=20),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='severity',
            field=models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch'), ('critical', 'Kritisch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warnung'), ('error', 'Fehler')], max_length=20),
        ),
    ]
