# Generated by Django 4.2.23 on 2025-07-04 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_platform_color_alter_platform_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('read', 'Datei gelesen'), ('write', 'Datei geschrieben'), ('delete', 'Datei gelöscht'), ('create', 'Datei erstellt'), ('rename', 'Datei umbenannt'), ('copy', 'Datei kopiert'), ('move', 'Datei verschoben'), ('list', 'Verzeichnis aufgelistet'), ('upload', 'Datei hochgeladen'), ('download', 'Datei heruntergeladen')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Erfolgreich'), ('failed', 'Fehlgeschlagen'), ('blocked', 'Blockiert'), ('unauthorized', 'Nicht autorisiert')], max_length=20)),
                ('file_path', models.CharField(max_length=1000)),
                ('original_path', models.CharField(blank=True, max_length=1000)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('security_level', models.CharField(default='normal', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('blocked_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dateioperation',
                'verbose_name_plural': 'Dateioperationen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='auto_block_suspicious_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='enable_audit_logging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='max_file_operations_per_hour',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='require_admin_for_sensitive_paths',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='server_directory_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='ssh_host',
            field=models.CharField(default='193.108.55.82', max_length=255),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='ssh_key_path',
            field=models.CharField(default='~/.ssh/id_rsa', max_length=500),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='ssh_user',
            field=models.CharField(default='ubuntu', max_length=100),
        ),
        migrations.CreateModel(
            name='ServerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000, unique=True)),
                ('path_type', models.CharField(choices=[('allowed', 'Erlaubter Pfad'), ('restricted', 'Eingeschränkter Pfad'), ('forbidden', 'Verbotener Pfad'), ('whitelist', 'Whitelist-Pfad')], max_length=20)),
                ('access_level', models.CharField(choices=[('read', 'Nur Lesen'), ('write', 'Lesen und Schreiben'), ('execute', 'Ausführen'), ('admin', 'Administrator'), ('none', 'Kein Zugriff')], max_length=20)),
                ('allow_read', models.BooleanField(default=True)),
                ('allow_write', models.BooleanField(default=False)),
                ('allow_delete', models.BooleanField(default=False)),
                ('allow_execute', models.BooleanField(default=False)),
                ('allow_list', models.BooleanField(default=True)),
                ('allowed_extensions', models.JSONField(blank=True, default=list)),
                ('forbidden_extensions', models.JSONField(blank=True, default=list)),
                ('max_file_size', models.BigIntegerField(blank=True, null=True)),
                ('require_admin', models.BooleanField(default=False)),
                ('require_confirmation', models.BooleanField(default=False)),
                ('risk_level', models.CharField(default='low', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server-Pfad',
                'verbose_name_plural': 'Server-Pfade',
                'ordering': ['path'],
                'indexes': [models.Index(fields=['path_type', 'is_active'], name='monitoring__path_ty_b592e2_idx'), models.Index(fields=['access_level', 'is_active'], name='monitoring__access__79823d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Erfolgreiche Anmeldung'), ('login_failed', 'Fehlgeschlagene Anmeldung'), ('unauthorized_access', 'Unbefugter Zugriff'), ('suspicious_activity', 'Verdächtige Aktivität'), ('permission_denied', 'Zugriff verweigert'), ('path_traversal', 'Pfad-Traversal-Versuch'), ('malicious_file', 'Schädliche Datei erkannt'), ('rate_limit_exceeded', 'Rate-Limit überschritten'), ('ssh_connection', 'SSH-Verbindung'), ('file_access_denied', 'Dateizugriff verweigert'), ('admin_action', 'Administrator-Aktion'), ('system_alert', 'System-Warnung')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warnung'), ('error', 'Fehler'), ('critical', 'Kritisch')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('url_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_file_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to='monitoring.fileoperation')),
            ],
            options={
                'verbose_name': 'Sicherheitsprotokoll',
                'verbose_name_plural': 'Sicherheitsprotokolle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fileoperation',
            index=models.Index(fields=['user_id', '-created_at'], name='monitoring__user_id_825778_idx'),
        ),
        migrations.AddIndex(
            model_name='fileoperation',
            index=models.Index(fields=['operation', 'status', '-created_at'], name='monitoring__operati_a1e819_idx'),
        ),
        migrations.AddIndex(
            model_name='fileoperation',
            index=models.Index(fields=['file_path', '-created_at'], name='monitoring__file_pa_e0897d_idx'),
        ),
        migrations.AddIndex(
            model_name='fileoperation',
            index=models.Index(fields=['status', '-created_at'], name='monitoring__status_c264a4_idx'),
        ),
        migrations.AddIndex(
            model_name='fileoperation',
            index=models.Index(fields=['security_level', '-created_at'], name='monitoring__securit_332fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['event_type', '-created_at'], name='monitoring__event_t_de5f29_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['severity', '-created_at'], name='monitoring__severit_a9585a_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['user_id', '-created_at'], name='monitoring__user_id_43c88b_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['ip_address', '-created_at'], name='monitoring__ip_addr_1dc854_idx'),
        ),
    ]
